# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# Build settings
markdown: kramdown
navigation:
 - text: Blog
   url: /
 - text: Projects
   url: /projects.html
 - text: About Me
   url: /about.html

projects:
 - title: Silk
   description: "Silky smooth profiling for Django"
   url: https://github.com/mtford90/silk
   img_url: /images/silk.png
 - title: Siesta
   description: "Object Mapping for Javascript" 
   url: http://mtford90.github.io/siesta/
   img_url: /images/siesta.png
 - title: Red Hot React
   description: "A boilerplate for ReactJS with emphasis on developer productivity"
   url: http://mtford90.github.io/red-hot-react
   img_url: /images/fire.png
 - title: Mosayc
   description: "Photo sharing like you've never seen before"
   url: http://mosayc.com
   img_url: /images/mosayc.jpg